###
POST http://localhost:3000/accounts
content-type: application/json

{
    "newAccount": "Tom"
}

###
POST http://localhost:3000/accounts
content-type: application/json

{
    "newAccount": "Jane"
}

###
POST http://localhost:3000/categories
content-type: application/json

{
    "newCategory": "house"
}

###
POST http://localhost:3000/transactions
content-type: application/json

{
  "newTransaction": {
    "accountId": 1, 
    "accountIdFrom": null, 
    "accountIdTo": null,
    "type": "Deposit", 
    "amount": 1000, 
    "categoryId": 1,
    "description": "April salary"
  }
}

###
POST http://localhost:3000/transactions
content-type: application/json

{
  "newTransaction": {
    "accountId": null,
    "accountIdFrom": 1, 
    "accountIdTo": 2,
    "type": "Transfer",
    "amount": 700,
    "categoryId": 2,
    "description": "May house rent"
  }
}


############

###
POST http://localhost:3000/accounts
content-type: application/json

{
    "newAccount": "Zoey"
}

###
POST http://localhost:3000/categories
content-type: application/json

{
    "newCategory": "food"
}

###
# POST http://localhost:3000/transactions
# content-type: application/json

# {
#   "newTransaction":"{\"accountId\":null,\"accountIdFrom\":1,\"accountIdTo\":2,\"type\":\"Transfer\",\"amount\":100,\"categoryId\":1,\"description\":\"salary april\"}"
# }




############

###
GET http://localhost:3000/accounts
content-type: application/json

###
GET http://localhost:3000/categories
content-type: application/json

###
GET http://localhost:3000/transactions
content-type: application/json